### ISSUE TITLE
Subscribe more then one topic for event in the same client

### ISSUE THREAD

**Issue by reedF** [deepstreamIO/deepstream.io-client-java#118]
Hi,can we Subscribe more then one topic for event in the same client,such as:
client.event.subscribe("event/a,event/b",listener)

or using regex pattern to match some topics:
client.event.subscribe("event/*",listener)

**Comment by yasserf** [comment]
You can't no, you have do it via 

client.event.subscribe("event/a",listener)
client.event.subscribe("event/b",listener)

due to how the subscription patterns work

**Comment by reedF** [comment]
@yasserf thx for your response
