### ISSUE TITLE
deepstream java v2.2.2 cannot login to deepstream server v4.2.5

### ISSUE THREAD

**Issue by Pitpy** [deepstreamIO/deepstream.io-client-java#143]
There are no error and nothing after login!

**Comment by yasserf** [comment]
which url are you connecting to?

**Comment by Pitpy** [comment]
> which url are you connecting to?

        DeepstreamClient ds = new DeepstreamClient("ws://10.0.10.40:6020");
        JsonObject credentials = new JsonObject();
        credentials.addProperty("user", "admin");
        credentials.addProperty("password", "chat@12");
        System.out.println(credentials);
        LoginResult result = ds.login(credentials);
        System.out.println(result);

**Comment by Pitpy** [comment]
@yasserf 
The IP is my organize LAN.
It's work for ds server v3, but not for v4.

**Comment by yasserf** [comment]
Yeah you need to connect to the V3 url

urlPath: /deepstream-v3

**Comment by Pitpy** [comment]
OK..., I changed to ds server v5 & use urlPath: /deepstream-v3 now working.
Thank you @yasserf
