### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by srossross** [deepstreamIO/deepstream.io-client-java#37]
Can you provide installation instructions in the Readme?

The install instructions here: https://deepstream.io/install/java/ tell me to add this to my pom.xml file.

```
    <dependency>
      <groupId>io.deepstream</groupId>
      <artifactId>deepstream.io-client-java</artifactId>
      <version>0.8</version>
      <type>pom</type>
    </dependency>
```

result in 

```
[WARNING] The POM for io.deepstream:deepstream.io-client-java:pom:0.8 is missing, no dependency information available
```

I assume because I don't have a bintray resolver?  But after searching for a while I thought I would ask here.

Sorry, but I a new to java/scala programming.

(Bonus points if you know how to do this in a `build.sbt` too)

Thanks.

**Comment by yasserf** [comment]
You need to point towards jCenter repo, I think maven resorts automatically to mavencentral

**Comment by srossross** [comment]
Is there an example java app I could look at?

**Comment by mattlisiv** [comment]
You can add JCenter as a repository by adding this to your pom.xml file:

```
<repositories>
        <repository>
            <id>jcenter</id>
            <url>https://jcenter.bintray.com/</url>
        </repository>
</repositories>
```

**Comment by yasserf** [comment]
Closing this issue, feel free to reopen if this is still an issue.

Also, although super late, heres a repo!

https://github.com/deepstreamIO/ds-demo-pizza-tracker/tree/master/android/PizzaTracker
