### ISSUE TITLE
rpc response timeout even after setting the rpcTimeout flag

### ISSUE THREAD

**Issue by Sheshagiri** [deepstreamIO/deepstream.io-client-java#68]
Looks like this is same as https://github.com/deepstreamIO/deepstream.io/issues/534  where the provider is sending RESPONSE_TIMEOUT even after setting the rpcTimeout  while creating the DeepstreamClient.

`Properties clientConfig = new Properties();
clientConfig.put("rpcTimeout", "400000");
clientConfig.put("rpcAckTimeout", "400000");
DeepstreamClient agent = new DeepstreamClient("ip:port",clientConfig);`

**Comment by AlexBHarley** [comment]
Closed [here](https://github.com/deepstreamIO/deepstream.io/issues/534)
