### ISSUE TITLE
mergeStrategy.merge- null object

### ISSUE THREAD

**Issue by lironsteren** [deepstreamIO/deepstream.io-client-java#72]
Exception java.lang.NullPointerException: Attempt to invoke interface method 'com.google.gson.JsonElement io.deepstream.RecordMergeStrategy.merge(io.deepstream.Record, com.google.gson.JsonElement, int)' on a null object reference
io.deepstream.Record.recoverRecord (Record.java:629)
io.deepstream.Record.applyUpdate (Record.java:589)
io.deepstream.Record.onMessage (Record.java:520)
io.deepstream.RecordHandler.handle (RecordHandler.java:297)
io.deepstream.Connection$4.run (Connection.java:218)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)

** its happen when changing from 4/3G to wifi and vice versa **

**Comment by AlexBHarley** [comment]
Closed by #78
