### ISSUE TITLE
Setting jsonpath values when jsonpath contains numeric value does set/sync properly client-side but writes proper value server-side.

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io-client-java#84]
Dev Note: this was discovered while testing with the java-client the two following and related  deepstream.io server (master/v2.2.0) issues:

1) Setting An element to an array with index = 0 creates an Object
https://github.com/deepstreamIO/deepstream.io/issues/646
2) Record Set JsonPath with numeric parts that are not array indices returned different results on client vs server side
https://github.com/deepstreamIO/deepstream.io/issues/651

I have submitted FIXes for the above server-side json-path resolver issues. See comments and attachments in issue#651  https://github.com/deepstreamIO/deepstream.io/issues/651.

Description of this java-client issue:

There is still a corner case with Java client (v2.0.8) see below (w redis cache plugin configured, all components running localhost/Mac osx, all latest versions):
e.g.

```
JsonObject newTixTextObj = new JsonObject();
newTixTextObj.addProperty("1","tt-1");
newTixTextObj.addProperty("2","tt-2");
newTixTextObj.addProperty("3","tt-3");
newTixTextObj.addProperty("4","tt-4");
newTixTextObj.addProperty("5","tt-5");
newTixTextObj.addProperty("6","tt-6");
                
Record rec_setPathNum = dsClient.record.getRecord("test/rec_setPathNum");
rec_setPathNum.set("a.b.4", newTixTextObj);
rec_setPathNum.set("aaa[1].333.bbb[0].222", newTixTextObj);
rec_setPathNum.set("a.b.0.2.xxx[4].a", newTixTextObj);
//rec_setPathNum.set("aaa[0].b.1.ccc[1].1", newTixTextObj);
JsonElement val = rec_setPathNum.get("aaa[0]");
rec_setPathNum.set("aaa[0].b", newTixTextObj);
val = rec_setPathNum.get("aaa[0]");

JsonElement rec_setPathNum_elem = rec_setPathNum.get();
System.out.println(">> rec_setPathNum.get() = " + rec_setPathNum_elem.toString());
rec_setPathNum.discard();

SnapshotResult rec_setPathNum_snap = dsClient.record.snapshot("test/rec_setPathNum");
System.out.println(">> rec_setPathNum SNAP = " + rec_setPathNum_snap.getData().toString());

rec_setPathNum = dsClient.record.getRecord("test/rec_setPathNum");
System.out.println(">> rec_setPathNum = " + rec_setPathNum_elem.toString());

```

rec_setPathNum.set("aaa[0].b") does not apply update on client-side BUT does update server-side with no errs logged.

I’ve tested and VERIFIED that the JAVA client corner case I sighted above ( rec_setPathNum.set(“aaa[0].b”, newTixTextObj); ) IS AN ISSUE with the JAVA-client somewhere. I haven’t traced the java-client side issue yet, but I did verify that the back-end/server/redis value is written correctly AND the above JAVA client SNAPSHOT call returns the correct data as well, but the java record that the “.set” is called on above does NOT reflect the correct updated server-side value. The client-side and server-side are NOT SYNC’D anymore in this use case.

**Comment by honorcode** [comment]
TO BE CLEAR: This java-client ISSUE was observed while testing my local build of my server-side (deepstream.io v2.2.0) json-path.js fixes attached (as .txt) in https://github.com/deepstreamIO/deepstream.io/issues/651.

**Comment by honorcode** [comment]
Tested again with deepstream server 2.2.0 and java client 2.0.8 and the result is not sync'd either but with different result values due to the broken parsing for numeric object member names as noted in https://github.com/deepstreamIO/deepstream.io/issues/651

**Comment by honorcode** [comment]
** FIX (see attachments below)

FYI the website link for the Contributor License Agreement is broken, so I couldn't do a PR but below is my deepstream.io-client-java/master patch with my FIXes (.txt -> .java source) for this client=side issue related to these server-side issues #651 and #646.

Summary: UtilJsonPath:setIterateThrough(...) : the fix is for array index items in path that are null -> add new object

                if (parentObject.get( prefix ).getAsJsonArray().get( index ).isJsonNull()) {
                    parentObject.get( prefix ).getAsJsonArray().set( index, new JsonObject() );
                }

Source and New Tests:
[UtilJSONPath.txt](https://github.com/deepstreamIO/deepstream.io-client-java/files/931864/UtilJSONPath.txt)
[JSONPathTest.txt](https://github.com/deepstreamIO/deepstream.io-client-java/files/931865/JSONPathTest.txt)

**Comment by yasserf** [comment]
Hey, thanks for raising and fixing. Can you raise a Pr? We'll solve cla issue on our side. Thanks!

**Comment by honorcode** [comment]
@yasserf, How do I raise a PR without a signed agreement?
I tried to push my local branch with commits and got a permissions error.
So how can I select a branch to make a PR off of?
Forgive my ignorance here if I'm missing something obvious.
I believe @AlexBHarley might have already done this.

**Comment by honorcode** [comment]
```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags --set-upstream origin refs/heads/honorcode/fix-jsonpath-arrays-empty-slot-and-numeric-obj-member-names:refs/heads/honorcode/fix-jsonpath-arrays-empty-slot-and-numeric-obj-member-names 
Pushing to https://github.com/deepstreamIO/deepstream.io-client-java.git
remote: Permission to deepstreamIO/deepstream.io-client-java.git denied to honorcode.
fatal: unable to access 'https://github.com/deepstreamIO/deepstream.io-client-java.git/': The requested URL returned error: 403
Completed with errors, see above
```

**Comment by honorcode** [comment]
Yes, @AlexBHarley already did this. :-)

**Comment by yasserf** [comment]
You'll need to create a fork, we dont add outside collaborators to the org due to pricing. Signing the CLA only means you don't hold the IP to the fix made.

Awesome, thanks @alex!
