### ISSUE TITLE
ExecutorService's for Event, Record, Record and Presence handlers are never explicitly shutdown

### ISSUE THREAD

**Issue by AlexBHarley** [deepstreamIO/deepstream.io-client-java#92]

**Comment by afiller** [comment]
That's a highly relevant change to enable the use of deepstream in web environments (Tomcat, JBoss etc.) where the application should be able to be started/stopped without stopping the whole JVM.

**Comment by AlexBHarley** [comment]
Closed in `v2.2.2`

**Comment by afiller** [comment]
It's not (completely) solved in 2.2.2:

(Remark: MC is my web application started/stopped on Tomcat 8)

`Jul 24, 2017 2:24:32 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [MC] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.FileDispatcherImpl.read0(Native Method)
 sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
 sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
 sun.nio.ch.IOUtil.read(IOUtil.java:197)
 sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
 org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:233)
 org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:12)
 org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:229)
 org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
 java.lang.Thread.run(Thread.java:748)
Jul 24, 2017 2:24:32 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [MC] appears to have started a thread named [pool-7-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:748)
Jul 24, 2017 2:24:32 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [MC] appears to have started a thread named [WebsocketWriteThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 org.java_websocket.SocketChannelIOHelper.writeBlocking(SocketChannelIOHelper.java:74)
 org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:440)
 java.lang.Thread.run(Thread.java:748)`

**Comment by AlexBHarley** [comment]
Thanks for letting us know. Do you have a snippet I can use to reproduce?

**Comment by afiller** [comment]
When starting up my web application I have a life cycle listener which calls the following methods at startup/shutdown of the application

startup:

`private DeepstreamCommunicationService(final String deepstreamHost,
			final String deepstreamUser, final String deepStreamPassword)
			throws Exception {
		host = deepstreamHost;

		if (deepstreamUser != null && !deepstreamUser.equals("")) {
			loginData = new JsonObject();
			loginData.addProperty("username", deepstreamUser);
			loginData.addProperty("password", deepStreamPassword);
		} else {
			loginData = null;
		}

		gson = new Gson();

		try {
			connectOrReconnect();
		} catch (final Exception e) {
			log.error("Problem when connecting to deepstream: {}",
					e.getMessage());
			throw e;
		}
	}

	public static DeepstreamCommunicationService start(
			final String deepstreamHost, final String deepstreamUser,
			final String deepStreamPassword) throws Exception {
		log.info("Starting service...");
		if (instance == null) {
			instance = new DeepstreamCommunicationService(deepstreamHost,
					deepstreamUser, deepStreamPassword);
		}
		log.info("Started.");
		return instance;
	}
`
At shutdown:

`	public void stop() throws Exception {
		log.info("Stopping service...");

		try {
			client.removeConnectionChangeListener(this);
			client.close();
			client = null;
		} catch (final Exception e) {
			log.warn("Could not close deepstream connection: {}",
					e.getMessage());
		}

		log.info("Stopped.");
	}`

The connect method is the following:

`	private void connectOrReconnect() throws Exception {
		log.info("Connecting to deepstream...");

		final Properties properties = new Properties();
		properties.setProperty(ConfigOptions.MAX_RECONNECT_ATTEMPTS.toString(),
				"10");

		client = DeepstreamFactory.getInstance().getClient(host, properties);
		client.addConnectionChangeListener(this);

		LoginResult result = null;
		do {
			log.debug("Trying to login...");

			if (loginData != null) {
				result = client.login(loginData);
			} else {
				result = client.login();
			}

			if (!result.loggedIn()) {
				log.warn("Login and authentication failed.");

				try {
					Thread.sleep(1000);
				} catch (final InterruptedException e) {
					// Do nothing
				}
			}
		} while (startupComplete && !result.loggedIn());

		if (result.loggedIn()) {
			log.debug("Login successful.");

			startupComplete = true;
			reconnecting = false;
			log.info("Connection to deepstream established.");

			provideMethods();

		} else {
			log.error("Could not login to deepstream server at startup: {}",
					result.getErrorEvent());
			throw new Exception(
					"Could not connect to deepstream server at startup!");
		}
	}`


It's a bit more complicated, but I need to ensure that the connection to deepsteam is automatically reconnected. So I'm also using a connection state change listener:

`	@Override
	public void connectionStateChanged(final ConnectionState connectionState) {
		if (startupComplete && connectionState == ConnectionState.CLOSED) {
			if (reconnecting) {
				log.warn("Deepstream connection still lost...");
			} else {
				log.warn("Deepstream connection lost!");
				reconnecting = true;
			}

			try {
				connectOrReconnect();
			} catch (final Exception e) {
				log.error(
						"Problem when reconnecting to deepstream deepstream: {}",
						e.getMessage());
			}
		}
	}`

If it's helpful for you I would setup a *very* simple Tomcat webapp for demonstration purposese somewhere on github?

**Comment by AlexBHarley** [comment]
Thanks for that, I created the following gist to try your code.

https://gist.github.com/AlexBHarley/8cddba70614d18453a72f63dcadc2dc2

Everything worked as expected.

![screen shot 2017-07-25 at 14 58 40](https://user-images.githubusercontent.com/11168524/28573106-c86d81a4-7149-11e7-8b40-9c67d7ab50c0.png)

I think it has more to do with your env (tomcat etc) and what you're doing with the client (writing to it in different threads). If you could set up a simple repository for me that'd be great.

**Comment by afiller** [comment]
Sorry for the late reply. It seems to be a problem in the interplay with Tomcat. I tested it with several versions and my problem still occurs. I pushed my testing project here:
https://bitbucket.org/afiller/ds-test/src/8a9dae5b0549fe8e19e3fddae575ebe3cd15351d/src/de/filler/test/deepstream/?at=master

The configuration for DS is done by system parameters (not to include login information in the repo).

The problem persists as you can see in the log file:

```
Aug 09, 2017 11:03:33 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNUNG: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:DS-Test' did not find a matching property.
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server version:        Apache Tomcat/8.0.45
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server built:          Jun 26 2017 20:06:07 UTC
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server number:         8.0.45.0
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: OS Name:               Mac OS X
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: OS Version:            10.12.6
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Architecture:          x86_64
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Java Home:             /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: JVM Version:           1.8.0_131-b11
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: JVM Vendor:            Oracle Corporation
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: CATALINA_BASE:         /Users/andreas/Dropbox/Dokumente/Cloud/MobileCoach/Development/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: CATALINA_HOME:         /Users/andreas/Dropbox/Dokumente/Cloud/MobileCoach/Development/Server/apache-tomcat-8.0.45
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dcatalina.base=/Users/andreas/Dropbox/Dokumente/Cloud/MobileCoach/Development/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dcatalina.home=/Users/andreas/Dropbox/Dokumente/Cloud/MobileCoach/Development/Server/apache-tomcat-8.0.45
Aug 09, 2017 11:03:33 AM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dwtp.deploy=/Users/andreas/Dropbox/Dokumente/Cloud/MobileCoach/Development/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps
Aug 09, 2017 11:03:33 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFORMATION: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /Users/andreas/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Aug 09, 2017 11:03:33 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-8080"]
Aug 09, 2017 11:03:34 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 09, 2017 11:03:34 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["http-nio-8443"]
Aug 09, 2017 11:03:34 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 09, 2017 11:03:34 AM org.apache.coyote.AbstractProtocol init
INFORMATION: Initializing ProtocolHandler ["ajp-nio-8009"]
Aug 09, 2017 11:03:34 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFORMATION: Using a shared selector for servlet write/read
Aug 09, 2017 11:03:34 AM org.apache.catalina.startup.Catalina load
INFORMATION: Initialization processed in 931 ms
Aug 09, 2017 11:03:34 AM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service Catalina
Aug 09, 2017 11:03:34 AM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet Engine: Apache Tomcat/8.0.45
Aug 09, 2017 11:03:34 AM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Starting service...
Connecting to deepstream...
Trying to login...
Login successful.
Connection to deepstream established.
Started.
Aug 09, 2017 11:03:35 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-8080"]
Aug 09, 2017 11:03:35 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-8443"]
Aug 09, 2017 11:03:35 AM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["ajp-nio-8009"]
Aug 09, 2017 11:03:35 AM org.apache.catalina.startup.Catalina start
INFORMATION: Server startup in 962 ms
Aug 09, 2017 11:03:39 AM org.apache.catalina.core.StandardServer await
INFORMATION: A valid shutdown command was received via the shutdown port. Stopping the Server instance.
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-nio-8080"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["http-nio-8443"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol pause
INFORMATION: Pausing ProtocolHandler ["ajp-nio-8009"]
Aug 09, 2017 11:03:39 AM org.apache.catalina.core.StandardService stopInternal
INFORMATION: Stopping service Catalina
Stopping service...
Stopped.
Aug 09, 2017 11:03:39 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNUNG: The web application [DS-Test] appears to have started a thread named [Thread-4] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.FileDispatcherImpl.read0(Native Method)
 sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
 sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
 sun.nio.ch.IOUtil.read(IOUtil.java:197)
 sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
 org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:233)
 org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:12)
 org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:229)
 org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
 java.lang.Thread.run(Thread.java:748)
Aug 09, 2017 11:03:39 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNUNG: The web application [DS-Test] appears to have started a thread named [pool-5-thread-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:748)
Aug 09, 2017 11:03:39 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNUNG: The web application [DS-Test] appears to have started a thread named [WebsocketWriteThread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 org.java_websocket.SocketChannelIOHelper.writeBlocking(SocketChannelIOHelper.java:74)
 org.java_websocket.client.WebSocketClient$WebsocketWriteThread.run(WebSocketClient.java:440)
 java.lang.Thread.run(Thread.java:748)
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-nio-8080"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["http-nio-8443"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol stop
INFORMATION: Stopping ProtocolHandler ["ajp-nio-8009"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-nio-8080"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["http-nio-8443"]
Aug 09, 2017 11:03:39 AM org.apache.coyote.AbstractProtocol destroy
INFORMATION: Destroying ProtocolHandler ["ajp-nio-8009"]
```

**Comment by afiller** [comment]
Sorry for the late reply, again! - It really must have been a problem of my tomcat setup, because after developing the application a bit further the problem is gone now. I think the issue can be closed.

**Comment by AlexBHarley** [comment]
@afiller thanks for letting us know
