### ISSUE TITLE
Others ws libs

### ISSUE THREAD

**Issue by hleb-albau** [deepstreamIO/deepstream.io-client-java#99]
Hello, 
Currently i use undertow ws client to connect to various endpoints. Is it possible to reuse undertow for connection to deepstream(reusing some part of your lib for creating messages)?

Thanks

**Comment by AlexBHarley** [comment]
@hleb-albau we allow passing in custom endpoints when you initialise the client. Take a look [here](https://github.com/deepstreamIO/deepstream.io-client-java/blob/master/src/main/java/io/deepstream/DeepstreamClient.java#L81). Although I'm not sure how it will work for you.

We'd definitely be interested in seeing what you come up with pairing deepstream and undertow though.
